// frontend/src/components/RooflineChart.tsx
import ReactECharts from 'echarts-for-react';

interface Props {
  ips: number;
  cacheMiss: number;
  peakMips?: number;
  memBwGbps?: number;
}

export function RooflineChart({ ips, cacheMiss, peakMips = 166400, memBwGbps = 102.4 }: Props) {
  const PEAK_MIPS = peakMips;
  const PEAK_BW_GBS = memBwGbps;
  const ridgeOI = PEAK_MIPS / ((PEAK_BW_GBS * 1e9) / 64 / 1e6);

  let safeOI = ridgeOI;
  if (cacheMiss > 0) {
    safeOI = Math.max(0.01, 100.0 / cacheMiss);
  }
  const safeMIPS = Math.max(1, ips / 1e6);

  // BW slope line: from OI=0.01 up to the ridge point
  const bwLineData: [number, number][] = [];
  for (let oi = 0.01; oi <= ridgeOI * 1.1; oi *= 1.12) {
    const perf = (oi * ((PEAK_BW_GBS * 1e9) / 64)) / 1e6;
    bwLineData.push([oi, Math.min(perf, PEAK_MIPS)]);
  }
  // Make sure we hit the ridge point exactly
  bwLineData.push([ridgeOI, PEAK_MIPS]);

  // Compute ceiling: flat line from ridge point to the right edge
  const computeLineData: [number, number][] = [];
  computeLineData.push([ridgeOI, PEAK_MIPS]);
  for (let oi = ridgeOI * 1.3; oi <= 10000; oi *= 1.5) {
    computeLineData.push([oi, PEAK_MIPS]);
  }
  computeLineData.push([10000, PEAK_MIPS]);

  // Y-axis max should accommodate peak MIPS with some headroom
  const yMax = Math.pow(10, Math.ceil(Math.log10(PEAK_MIPS * 1.5)));

  const option = {
    backgroundColor: 'transparent',
    tooltip: { 
      trigger: 'item', 
      backgroundColor: '#0F172A', 
      borderColor: '#334155', 
      textStyle: { color: '#F8FAFC', fontFamily: 'Space Grotesk, monospace', fontSize: 11 },
      formatter: (params: any) => {
        if (params.seriesName === 'Live Workload') {
          const [oi, mips] = params.data as [number, number];
          return `<div class="font-mono text-[10px] uppercase text-slate-500 mb-1">Live Workload</div>
                  <div class="flex justify-between gap-4"><span>OI:</span><span class="text-blue-400">${oi.toFixed(6)}</span></div>
                  <div class="flex justify-between gap-4"><span>MIPS:</span><span class="text-blue-400">${mips.toLocaleString(undefined, { maximumFractionDigits: 4 })}</span></div>`;
        }
        return params.seriesName;
      }
    },
    grid: { top: 30, right: 35, bottom: 40, left: 60 },
    xAxis: {
      type: 'log', name: 'OPERATIONAL INTENSITY (Ops/Byte)', nameLocation: 'middle', nameGap: 25, min: 0.01, max: 10000,
      axisLabel: { color: '#94A3B8', fontFamily: 'Space Grotesk, monospace', fontSize: 10 }, splitLine: { lineStyle: { color: '#1E293B' } }, axisLine: { lineStyle: { color: '#475569' } },
      nameTextStyle: { color: '#64748B', fontFamily: 'Inter', fontSize: 10, fontWeight: 600 }
    },
    yAxis: {
      type: 'log', name: 'MIPS', min: 1, max: yMax,
      axisLabel: { color: '#94A3B8', fontFamily: 'Space Grotesk, monospace', fontSize: 10 }, splitLine: { lineStyle: { color: '#1E293B' } }, axisLine: { lineStyle: { color: '#475569' } },
      nameTextStyle: { color: '#64748B', fontFamily: 'Inter', fontSize: 10, fontWeight: 600 }
    },
    series: [
      { name: 'Memory BW Roof', type: 'line', data: bwLineData, symbol: 'none', lineStyle: { color: '#0D9488', width: 3, type: 'solid' }, z: 10 },
      { name: 'Compute Roof', type: 'line', data: computeLineData, symbol: 'none', lineStyle: { color: '#DC2626', width: 3, type: 'solid' }, z: 10 },
      {
        name: 'Live Workload', type: 'scatter', data: [[safeOI, safeMIPS]], symbolSize: 16, z: 20,
        itemStyle: { color: '#3B82F6', borderColor: '#BFDBFE', borderWidth: 3 },
        label: { show: true, position: 'top', formatter: 'WORKLOAD', fontFamily: 'Inter', fontSize: 9, color: '#93C5FD', fontWeight: 600 }
      }
    ]
  };

  return (
    <div className="bg-slate-800 border border-slate-700 flex flex-col h-full w-full">
      <div className="px-3 py-2 border-b border-slate-700 bg-slate-800/50 flex items-center justify-between shrink-0">
        <h3 className="text-[10px] md:text-xs font-semibold tracking-widest text-slate-300 uppercase">Architecture Roofline</h3>
        <div className="flex gap-3 items-center">
          <span className="flex items-center gap-1 text-[8px] font-mono"><span className="w-3 h-0.5 bg-[#0D9488] inline-block"></span><span className="text-slate-500">MEM BW</span></span>
          <span className="flex items-center gap-1 text-[8px] font-mono"><span className="w-3 h-0.5 bg-[#DC2626] inline-block"></span><span className="text-slate-500">COMPUTE</span></span>
          <span className="text-[8px] md:text-[9px] font-mono text-[#DC2626] border border-[#DC2626]/50 px-1 rounded-sm bg-red-500/10">BOUNDARY</span>
        </div>
      </div>
      <div className="p-0 h-full flex-1 w-full bg-[#0F172A]/50">
        <ReactECharts option={option} opts={{ renderer: 'svg' }} style={{ height: '100%', width: '100%' }} />
      </div>
    </div>
  );
}

// frontend/src/lib/RooflineChart.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { hwConfig } from "$lib/hwConfig";
  import * as echarts from "echarts";

  let chartContainer: HTMLDivElement;
  let chart: echarts.ECharts;
  let interval: ReturnType<typeof setInterval>;
  let ro: ResizeObserver;

  const VM = "/api/v1/query";

  onMount(async () => {
    chart = echarts.init(chartContainer);
    ro = new ResizeObserver(() => {
      if (chart) chart.resize();
    });
    ro.observe(chartContainer);

    buildChart();
    await fetchData();
    interval = setInterval(fetchData, 5000);
  });

  // Rebuild whenever config changes (store subscription via $: reactive)
  $: if (chart && $hwConfig) buildChart();

  function buildChart() {
    const PEAK_MIPS = $hwConfig.specs.peak_mips || 120000;
    const PEAK_BW_GBS = $hwConfig.specs.max_mem_bw_gbps || 59.7;

    // Ridge point: where memory ceiling meets compute ceiling
    const ridgeOI = PEAK_MIPS / ((PEAK_BW_GBS * 1e9) / 64 / 1e6);

    // Memory bandwidth roof: MIPS = OI × BW (bytes/s) / 64 / 1e6
    const bwLineData: [number, number][] = [];
    for (let oi = 0.001; oi <= ridgeOI * 1.2; oi *= 1.15) {
      const mips = (oi * ((PEAK_BW_GBS * 1e9) / 64)) / 1e6;
      bwLineData.push([oi, Math.min(mips, PEAK_MIPS)]);
    }

    // Compute ceiling: flat line from ridge OI onwards
    const computeLineData: [number, number][] = [];
    for (let oi = ridgeOI * 0.9; oi <= 1000; oi *= 1.3) {
      computeLineData.push([oi, PEAK_MIPS]);
    }

    chart.setOption(
      {
        color: ['blue', 'red', 'lightblue'],
        title: {
          text: "Roofline Model",
          subtext: "Dell PowerEdge R720 (2x Intel Xeon E5-2670) · H&P Ch.4",
          textStyle: {
            color: "#f1f5f9",
            fontSize: 16,
            fontFamily: "Inter, system-ui, sans-serif",
            fontWeight: 700
          },
          subtextStyle: { color: "#94a3b8", fontSize: 11, fontFamily: "Inter, system-ui, sans-serif" },
          top: 12,
          left: 16,
        },
        tooltip: {
          trigger: "item",
          backgroundColor: "rgba(15, 23, 42, 0.95)",
          borderColor: "#334155",
          textStyle: { color: "#f8fafc", fontFamily: "Inter, sans-serif", fontSize: 11 },
          formatter: (p) => {
            if (p.seriesName === "Workload") {
              return `<b>Current Workload</b><br/>OI: ${p.value[0].toFixed(2)} ops/byte<br/>Perf: ${p.value[1].toLocaleString(undefined, {maximumFractionDigits:0})} MIPS`;
            }
            return p.seriesName;
          },
        },
        legend: {
          data: ["Memory BW Roof", "Compute Roof", "Workload"],
          top: 14,
          right: 24,
          textStyle: { color: "#94a3b8", fontSize: 11, fontFamily: "Inter, sans-serif", fontWeight: 500 },
        },
        grid: { top: "22%", right: "6%", bottom: "14%", left: "12%" },
        xAxis: {
          type: "log",
          name: "Operational Intensity (Instr / Cache-Miss × 64B)",
          nameTextStyle: {
            color: "#94a3b8",
            fontSize: 11,
            fontFamily: "Inter, sans-serif",
            padding: [10, 0, 0, 0],
          },
          nameLocation: "middle",
          nameGap: 30,
          min: 0.01,
          max: 1000,
          axisLabel: { color: "#64748b", fontSize: 10, fontFamily: "Inter, sans-serif" },
          splitLine: { show: true, lineStyle: { color: "#1e293b" } },
          minorSplitLine: { show: true, lineStyle: { color: "rgba(30, 41, 59, 0.4)" } },
          axisLine: { lineStyle: { color: "#334155" } },
        },
        yAxis: {
          type: "log",
          name: "Performance (MIPS)",
          nameTextStyle: { color: "#94a3b8", fontSize: 11, fontFamily: "Inter, sans-serif" },
          min: 1,
          max: PEAK_MIPS * 2,
          axisLabel: { color: "#64748b", fontSize: 10, fontFamily: "Inter, sans-serif" },
          splitLine: { show: true, lineStyle: { color: "#1e293b" } },
          minorSplitLine: { show: true, lineStyle: { color: "rgba(30, 41, 59, 0.4)" } },
          axisLine: { lineStyle: { color: "#334155" } },
        },
        series: [
          {
            name: "Memory BW Roof",
            type: "line",
            data: bwLineData,
            smooth: false,
            symbol: "none",
            lineStyle: { color: "blue", width: 3, type: "dashed" },
            areaStyle: { color: "rgba(0, 0, 255, 0.06)" },
            z: 1,
            markPoint: {
              symbol: "none",
              label: { show: true, formatter: "{b}" },
              data: [
                {
                  coord: [ridgeOI * 0.015, PEAK_MIPS * 0.02],
                  name: "Memory-Bound",
                  label: { color: "rgba(0, 0, 255, 0.12)", fontSize: 26, fontWeight: "bold", fontFamily: "Inter, sans-serif" }
                },
                {
                  coord: [ridgeOI * 0.05, ((ridgeOI * 0.05 * ((PEAK_BW_GBS * 1e9) / 64)) / 1e6) * 1.5],
                  name: `Peak Mem BW: ${PEAK_BW_GBS.toFixed(1)} GB/s`,
                  label: { color: "#94a3b8", fontSize: 11, fontFamily: "Inter, sans-serif", rotate: 36 }
                }
              ]
            }
          },
          {
            name: "Compute Roof",
            type: "line",
            data: computeLineData,
            smooth: false,
            symbol: "none",
            lineStyle: { color: "red", width: 3, type: "dashed" },
            z: 1,
            markPoint: {
              symbol: "none",
              label: { show: true, formatter: "{b}" },
              data: [
                {
                  coord: [ridgeOI * 4, PEAK_MIPS * 0.02],
                  name: "Compute-Bound",
                  label: { color: "rgba(255, 0, 0, 0.08)", fontSize: 26, fontWeight: "bold", fontFamily: "Inter, sans-serif" }
                },
                {
                  coord: [ridgeOI * 4, PEAK_MIPS * 0.75],
                  name: `Peak Compute: ${PEAK_MIPS.toLocaleString()} MIPS`,
                  label: { color: "#94a3b8", fontSize: 11, fontFamily: "Inter, sans-serif" }
                }
              ]
            },
            markLine: {
              symbol: ["none", "none"],
              lineStyle: { color: "#475569", width: 1, type: "dotted" },
              label: { show: true, position: "start", formatter: "Ridge OI ≈ 100", color: "#64748b", fontSize: 10, fontFamily: "Inter, sans-serif" },
              data: [ { xAxis: ridgeOI } ]
            }
          },
          {
            name: "Workload",
            type: "scatter",
            data: [],
            symbolSize: 18,
            itemStyle: {
              color: "#7dd3fc",
              borderColor: "#38bdf8",
              borderWidth: 2,
              shadowColor: "rgba(56, 189, 248, 0.6)",
              shadowBlur: 14,
            },
            z: 10,
          },
        ],
        backgroundColor: {
          type: 'radial',
          x: 0.5, y: 0.5, r: 0.7,
          colorStops: [
            { offset: 0, color: 'rgba(15, 23, 42, 0.4)' },
            { offset: 1, color: 'transparent' }
          ]
        },
      },
      true
    ); // true = notMerge, forces full rebuild
  }

  onDestroy(() => {
    if (ro) ro.disconnect();
    if (interval) clearInterval(interval);
    if (chart) chart.dispose();
  });

  async function fetchData() {
    const node = $hwConfig.node_name;
    try {
      const [instR, missR] = await Promise.all([
        fetch(`${VM}?query=hqud_cpu_cpi{host="${node}"}`).then((r) => r.json()),
        fetch(`${VM}?query=hqud_cpu_cache_miss_rate{host="${node}"}`).then(
          (r) => r.json(),
        ),
      ]);

      const ipsR = await fetch(
        `${VM}?query=hqud_cpu_ips{host="${node}"}`,
      ).then((r) => r.json());

      let cpi = 0,
        missRate = 0;
      if (instR.status === "success" && instR.data.result.length > 0) {
        cpi = parseFloat(instR.data.result[0].value[1]);
      }
      if (missR.status === "success" && missR.data.result.length > 0) {
        missRate = parseFloat(missR.data.result[0].value[1]);
      }

      let ips = 0;
      if (ipsR.status === "success" && ipsR.data.result.length > 0) {
        ips = parseFloat(ipsR.data.result[0].value[1]);
      }

      let safeOI = 1000.0;
      if (missRate > 0) {
        safeOI = Math.max(0.01, 100.0 / missRate);
      }
      const safeMIPS = Math.max(1, ips / 1e6);

      chart.setOption({
        series: [
          { name: "Workload", data: [[safeOI, safeMIPS]] },
        ],
      });
    } catch (e) {
      console.error("Roofline fetch error", e);
    }
  }
</script>

<div style="position:relative; width:100%; height:100%;">
  <div bind:this={chartContainer} style="position:absolute; inset:0;"></div>
</div>
